version: '2'
services:
    seahorsegateway-app:
        image: seahorsegateway
        external_links:
            - seahorsegateway-postgresql:postgresql
            # Uncomment to have Cassandra working with the gateway
            # - seahorsegateway-cassandra:cassandra
            - seahorsegateway-elasticsearch:elasticsearch
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_CLOUD_CONFIG_URI=http://admin:admin@registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/seahorsegateway
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandra
            - JHIPSTER_SLEEP=30 # gives time for the cassandra cluster to start and execute the migration scripts
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 13782:13782
    seahorsegateway-postgresql:
        extends:
            file: postgresql.yml
            service: seahorsegateway-postgresql
        # Uncomment to have Cassandra working with the gateway
        # extends:
        #     file: cassandra-cluster.yml
        #     service: seahorsegateway-cassandra
    seahorsegateway-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: seahorsegateway-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
